apiVersion: v1
data:
  prometheus.yml: "global:\n  scrape_interval: 15s\n  scrape_timeout: 10s\n  evaluation_interval:
    15s\n\nalerting:\n  alertmanagers:\n  - follow_redirects: true\n    enable_http2:
    true\n    scheme: http\n    timeout: 10s\n    api_version: v2\n    static_configs:\n
    \   - targets: []\n\nscrape_configs:\n  - job_name: prometheus\n    honor_timestamps:
    true\n    scrape_interval: 15s\n    scrape_timeout: 10s\n    metrics_path: /metrics\n
    \   scheme: http\n    follow_redirects: true\n    enable_http2: true\n    static_configs:\n
    \     - targets:\n        - localhost:9090\n  \n  - job_name: 'fastapi'\n    scrape_interval:
    10s\n    metrics_path: /metrics\n    static_configs:\n      - targets: ['web:8000']\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-server-config
